version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker_files/dockerfile
    working_dir: /application
    # The top mount mounts the local source code into the container for compilation and running.
    # The other mounts effectively function as exclusions on the top mount, to prevent build artifacts from being created locally (as root).
    # Some of the other mounts are mapped to docker volumes to improve build-on-build performance by caching the build artifacts.
    # To completely clean the volumes, execute `docker-compose down -v` in a shell. A subsequent `docker-compose up` will run in a fresh environment.
    volumes:
      - .:/application:cached
      - /application/.elixir_ls
      - app-build:/application/_build
      - app-deps:/application/deps
      - app-mix:/root/.mix
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOSTNAME: postgres
      MIX_ENV: dev_docker
    ports:
      - 4000:4000
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: music_meta

volumes:
  app-build:
  app-deps:
  app-mix:
