FROM elixir:1.11-slim

# [inotify-tools] required for Phoenix live-reloading
# [git] required for devcontainer functioning

RUN apt-get update && \
    apt-get install -y inotify-tools git && \
    mix do local.hex --force, local.rebar --force
# set build ENV

ENV MIX_ENV=prod
ENTRYPOINT ["/bin/bash"]
CMD ["mix","deps.get"]
CMD ["mix","ecto.migrate"]
CMD ["mix","ecto.create"]
CMD ["mix","phx.server"]
CMD ["-c", "while sleep 1000; do :; done"]


# RUN MIX_ENV=prod mix do deps.get, compile

